draw_set_color(c_black)
draw_sprite(hud,0,0,0)
ecs=138
why=9+98/2
slottyoa=0
slotty=slot[slottyoa]
reload[slottyoa]-=1
hasplant=true
repeat(maxslots)
{
reload[slottyoa]-=1
hasplant=true


if(hasplant)
{
	slotty=slot[slottyoa]
	pacc=0
if(variable_struct_exists(plants.plant[slotty],"lawn"))
		{
			if(plants.plant[slotty].lawn==tilemud)
			{
				pacc=1
			}
			if(plants.plant[slotty].lawn==tilesand)
			{
				pacc=2
			}
			if(plants.plant[slotty].lawn==tilevolcano)
			{
				pacc=3
			}
			if(plants.plant[slotty].lawn==tiledesert)
			{
				pacc=4
			}
		}
		else
		{
			draw_sprite(tilestore, 0, ecs + 32, why);
		}
draw_sprite(Sprite178,pacc,ecs+32,why+4)
draw_sprite(object_get_sprite(plants.plant[slotty].object),0,ecs+32,why)
draw_sprite(Sprite176,pacc,ecs+32,why+4)
draw_text(ecs+5,why+30,string_hash_to_newline(string(plants.plant[slotty].cost)))
draw_healthbar(ecs,why-33,ecs+64,why+31,(reload[slottyoa]/plants.plant[slotty].recharge)*100,c_black,c_black,c_black,0,false,false)
if(keyboard_check_pressed(ord(slottyoa+1)))
{
if(stats.sunny>=plants.plant[slotty].cost&&reload[slottyoa]<=0)
{
instance_destroy(placer)
inst=instance_create(x,y,placer)
inst.slot=slotty
inst.slotselected=slotty
}
}
if(device_mouse_x_to_gui(0)<ecs+64&&device_mouse_x_to_gui(0)>ecs&&device_mouse_y_to_gui(0)<why+32&&device_mouse_y_to_gui(0)>why-32||point_in_rectangle(global.Touch_X, global.Touch_Y, ecs, 0, ecs+64, 64))
{
if(mouse_check_button_pressed(mb_left)||global.tapping)
{
	if(instance_exists(placer))
	{
	instance_destroy(placer)
}
if(stats.sunny>=plants.plant[slotty].cost&&reload[slottyoa]<=0)
{
instance_destroy(placer)
inst=instance_create(x,y,placer)
inst.slot=slotty
inst.slotselected=slottyoa
}
}
}
ecs+=75
slottyoa+=1
slotty+=1
}
}
draw_rectangle(ecs,0,ecs+128+32,64,true)
draw_text(ecs,0,"plant food: "+string(pf)+"/"+string(pfcap))
if(pf>0&&device_mouse_x_to_gui(0)<ecs+128+32&&device_mouse_x_to_gui(0)>ecs&&device_mouse_y_to_gui(0)<64&&device_mouse_y_to_gui(0)>0&&mouse_check_button_pressed(mb_left))
{
	inst=instance_create(x,y,plantfood)
}
ecs+=128+32
draw_rectangle(ecs,0,ecs+128,64,true)
draw_text(ecs,0,"shovel")
if(device_mouse_x_to_gui(0)<ecs+128&&device_mouse_x_to_gui(0)>ecs&&device_mouse_y_to_gui(0)<64&&device_mouse_y_to_gui(0)>0&&mouse_check_button_pressed(mb_left)||point_in_rectangle(global.Touch_X, global.Touch_Y, ecs, 0, ecs+128, 64)&&global.tapping)
{
	inst=instance_create(x,y,shovel)
}
ecs+=128
draw_healthbar(ecs,0,ecs+128,64,((stats.num+1)/stats.mnum)*100,c_black,c_red,c_green,0,true,true)
draw_text(33,87,string_hash_to_newline(string(stats.sunny)))