if(!place_meeting(x,y,plant1)&&can)
{
inst=instance_create(x,y,plants.plant[slot].object)
stats.sunny-=plants.plant[slot].cost
slots.reload[slotselected]=plants.plant[slot].recharge
if(variable_struct_exists(plants.plant[slot],"waterplant"))
{
	inst.waterboi=true
}
else
{
	inst.waterboi=false
}
}
action_kill_object();
