if(i<=0)
{
hp-=1
i=20
withered=true
alarm[0]=360
if(choose(0,1))
{
	inst=instance_create(x,y-6,bullet19)
	inst.speed=5
	inst.direction=other.direction+90
	inst=instance_create(x,y-6,bullet19)
	inst.speed=5
	inst.direction=other.direction-90
	instance_destroy(other)
}
}