/// @description kill
if(hp<=0)
{
instance_destroy()
}

if(pfactive)
{
	doubled=true
}
if(instance_exists(basiczombie))
{
inst=instance_nearest(x,y,basiczombie)
dir=point_direction(x,y,inst.x,inst.y)
inst=instance_furthest(x,y,basiczombie)
odir=point_direction(x,y,inst.x,inst.y)
if(collision_point(inst.x,inst.y,tiletypesteam,true,true))
{
	dir=random_range(-45,45)
}
}
else
{
	dir=0
}
if(mouse_check_button(mb_right))
{
	dir=point_direction(x,y,mouse_x,mouse_y)
}