col=collision_line(x,y,x+128,y,basiczombie,false,true)
iy-=1
i-=1
if(col&&!ate&&iy<=0)
{
	sh-=1
	if(sh<=0)
	{
	sprite_index=chomperswallow
	col.hp-=30
	stats.dps+=30
	while(image_number+sprite_get_number(chomperswallow)<4)
	{
		sh+=1
		image_number+=1
	}
	sh=sprite_get_number(chomperswallow)*(room_speed/sprite_get_speed(chomperswallow))
	}
	if(col.hp<=0)
	{
		ate=true
		image_index=0
		sprite_index=chompysleepstart
		i=sprite_get_number(chompysleepstart)*(room_speed/sprite_get_speed(chompysleepstart))
		iy=reload*4
	}
}
else if(ate&&i<=0)
{
	sprite_index=chompysleep
	if(iy<=0)
	{
		image_index=0
		sprite_index=chompysleepend
		iy=image_number*(room_speed/sprite_get_speed(sprite_index))
		ate=false
	}
}
else if(iy>0)
{
	sprite_index=chompysleepend
}
else if (i>0&&ate)
{
	sprite_index=chompysleepstart
}
else
{
	sprite_index=chompyboi
}

///kill
if(hp<=0)
{
instance_destroy()
}
col=collision_line(x,y,room_width,y,basiczombie,false,true)
if(pfactive)
{
	instance_destroy(col)
}