sh-=((obj_mic.microphone_volume)/100)+0.1
yscale=(obj_mic.microphone_volume/2000)+0.1
if(sh<=0)
{
inst=instance_create(x,y+6,bullet21)
inst.hspeed=5
inst.image_xscale=yscale
inst.image_yscale=yscale
sh=reload
}

///kill
if(hp<=0)
{
instance_destroy()
}

if(pfactive)
{
	pfi-=1
	if(pfi<=0)
	{
		audio_play_sound(pop,1000,false)
		inst=instance_create(x,y+random_range(-6,6),bullet21)
		inst.hspeed=5
		inst.image_xscale=yscale
		inst.image_yscale=yscale
		pfi=pfr
	}
}